name: MirrorBot Environment

on:
  push:
  workflow_dispatch:
   

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      

      - name: Set Git Configs & Secrets
        run: |
          
          git config --global credential.helper store
          echo "https://github.com/ripan04/AutoAnimeBot" > ~/.git-credentials

      - name: Clone Mirror Repo
        run: |
          git clone https://github.com/ripan04/AutoAnimeBot source

      - name: Compile Docker
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot

      - name: Run bot
        continue-on-error: true
        timeout-minutes: 340
        run: |
          docker run --privileged --rm -i mirror-bot

      - name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://github.com/ripan04/AutoAnimeBot loop
          cd loop || exit 1
          git commit --allow-empty -m "Workflow: Loop"
          git push -f
